### PR TITLE
Add the packaging metadata to build the metalsmith snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

If we upload the snap to the ubuntu store we will get a great way to deliver the software, and get transactional automatic updates. I've been testing the snap and it seems to me good enough to publish in the edge channel, which will make it really easy to do crowd-testing before the stable release.

If you have any doubts or comments, please let me know :)

[1] https://gist.github.com/elopio/2aacc0a2fe66dc9cbdce7cf25bc5dd4f

**Comment by woodyrew** [comment]
Hi, seems like a reasonable PR for the Metalsmith-CLI however I wanted to find out about how Metalsmith will behave with snapcraft.

Metalsmith doesn't do very much by its self, it requires plugins (npm packages or custom code) and a config file to coordinate how they behave. Is that something that could be done with Snapcraft?

**Comment by elopio** [comment]
Hey @woodyrew, thanks for reviewing this. As you said, this is for the CLI, which mostly serves as a showcase, it's not useful for people using metalsmith as a library. I had some fun trying the other examples and I think there are some potential uses. For example, you could bundle metalsmith, together with your plugins, npm, node and your content into a snap. Then you have your whole site + it's dependencies in a package that's installable in many linux distros. You probably wouldn't want to publish this in the store, but the store has a feature for private snaps that makes sense for this case. However, I'm not sure how compelling this would be for your current users who are used to npm to install everything.
The other use case I thought was packaging a bundle of node+metalsmith+npm packages. So people could make and deliver products on top of metalsmith. The users of those products just add their content, maybe tweak the theming a little, and deploy their site without having to install any additional plugins by themselves.

What do you think? Makes sense?

pura vida.

**Comment by Ajedi32** [comment]
I'm a little bit skeptical of how useful a Snap version of metalsmith would really be in either of those use cases. Then again I'm not really all that familiar with Snaps, so maybe you can clarify.

> You could bundle metalsmith, together with your plugins, npm, node and your content into a snap. Then you have your whole site + it's dependencies in a package that's installable in many linux distros.

How would Metalsmith existing as a Snap make this easier? They'd still have to use NPM for all the other dependencies, right? And if they're creating their own Snap to bundle other non-Metalsmith NPM packages with their site, why couldn't they just use that same process to include Metalsmith in their bundle? Based on the content of this PR, wouldn't bundling Metalsmith already be as simple as including `plugin: nodejs` in their Snapcraft file?

Also, if users want to publish their site as a Snap, why would they include Metalsmith as part of that package? Static sites are just that - static. Building them (which is the part that requires Metalsmith) is usually something that happens prior to deployment, not in the production environment.

> The other use case I thought was packaging a bundle of node+metalsmith+npm packages. So people could make and deliver products on top of metalsmith. The users of those products just add their content, maybe tweak the theming a little, and deploy their site without having to install any additional plugins by themselves.

That's actually a pretty interesting use case. But again, how does Metalsmith existing as a Snap make this sort of thing any easier to develop? Snapcraft already seems to have really good support for bundling NPM packages as part of the Snap, why would you want to use a separate part for that?

**Comment by elopio** [comment]
Hello @Ajedi32. You are right, metalsmith as a snap is useful only for the CLI. I was just trying to reply to the question about the most common use of metalsmith as a library, not related to this PR.

The other use cases involve making another snap, with metalsmith only as a part of the bundle. Reading your comment makes me realize that my first example is actually not that useful, you might want your site to be installable everywhere, not buildable everywhere. So yes, it doesn't make a lot of sense to have metalsmith and the dependencies together with the content, and if you strip out the content is the same as the second scenario. What might be useful is to ship the generated content + a web server in a snap.

**Comment by Ajedi32** [comment]
> You are right, metalsmith as a snap is useful only for the CLI

That kinda comes back to @woodyrew's original point though. Metalsmith (including the CLI, not just the library) is almost entirely reliant on plugins - it's not very useful on it's own.

So with that in mind, how would this Snap version of the Metalsmith CLI handle Metalsmith plugins? Does it work with npm packages installed through the usual means? Or does it have its own isolated environment for npm packages? If the latter, how would a person using this Snapped version of Metalsmith install a plugin for it?

**Comment by elopio** [comment]
It will work with npm packages installed through the usual means. And as npm and node are bundled in the snap, you can use those.
Take a look at how I build the example site in my gist: https://gist.github.com/elopio/2aacc0a2fe66dc9cbdce7cf25bc5dd4f

**Comment by Ajedi32** [comment]
In that case, this seems fine to me. Anyone else have any objections/questions/concerns?

**Comment by woodyrew** [comment]
None from me either.

On a side note: What are the differences between Snapcraft and Docker?

**Comment by elopio** [comment]
Well, the approaches are pretty different. Docker images include the operating system, and the communication between apps is generally through the network. Snaps instead use well-defined interfaces to decide which services provided by the host operating system and by other snaps can be consumed, so you can communicate in many different ways like network, unix socket, dbus. That is the `plugs` section in the yaml file. In this case, the snap has the home interface, so it can read and write to the home directory. In order to do that in docker you would have to mount the directory. So snaps are a lighter way to isolate apps, and offer the user and the developer more control about what's allowed and what is not.
In the end, you can mix and match depending on your requirements and your preference. We have snaps for docker and lxd, so even in an ubuntu all-snap installation, you could have snaps talking to services in containers.
We are writing snaps because we need a solution that works for phones, laptops, metal servers, the cloud and iot devices. Write one yaml, work everywhere.

**Comment by woodyrew** [comment]
Sounds interesting. Thanks for taking the time to explain. :smile:

**Comment by elopio** [comment]
Thanks to you for the review. Here's how you can push the snap to the store, let me know if you need a hand with that:
http://snapcraft.io/docs/build-snaps/publish
And we are all trying to make snapcraft a pleasure for all developers. If you have any complaints or suggestions, they will be highly appreciated.

**Comment by popey** [comment]
Hello. I noticed that the Metalsmith snap didn't make it into the snappy store yet. Is there a problem we can help with to get it uploaded?

**Comment by Ajedi32** [comment]
See #270. I haven't quite gotten around to creating a shared account for the Metalsmith Org yet. I'll give it a try sometime tomorrow...

**Comment by popey** [comment]
Hiya, did you manage to get this pushed to the store? If there are problems in the sign-up process I'd like us to get them reported and fixed with the store team.

**Comment by Ajedi32** [comment]
Well, I _think_ I have the name registered now. Still need to experiment with getting the Snap built on my development environment though. Looks like I'm going to need a Linux VM? (I'm currently running Windows.)

**Comment by popey** [comment]
That's certainly one option. The other alternative is to let it build in Launchpad (our build service) which would probably work out easier for you and better in the long run. That way you can have it auto-build on any changes landing, and auto-upload to the store for you. The documentation is at the link below under "Using Launchpad":-

https://snapcraft.io/docs/build-snaps/ci-integration

If however you do want to build locally, I'd recommend an Ubuntu 16.04.2 server iso from the link below. That way it will be leaner (no GUI) and you can use the snapcraft commands directly in it. If using bridged networking in the virtual machine (like VirtualBox) you can access any running services (like metalsmith) from outside the VM over the network.

http://releases.ubuntu.com/16.04/ubuntu-16.04.2-server-amd64.img

**Comment by Ajedi32** [comment]
I think we may end up doing it with Travis, since we've already got a build going for that on #270, and it's nice to have everything consolidated in one tool.

That said, I'll probably try it out locally first just to get a feel for what the CI should be doing.

**Comment by elopio** [comment]
@Ajedi32 hello again! I'm came back because we have great new service that I think you will like. Take a look at https://build.snapcraft.io/
With a couple of clicks you can set up the metalsmith package, and it will take care of building and continuous delivery to the store.
It's in beta, so please let me know what do you think.

**Comment by Ajedi32** [comment]
Thanks, I'll take a look. Sorry for taking so long to get to this; I've had other projects I've been working on lately so I haven't had much time to work on Metalsmith.

**Comment by elopio** [comment]
no need to apologize, we appreciate a lot your time and comments so far.

**Pull request merged**
