### PR TITLE
Swap chalk for turbocolor.

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hi @Ajedi32, @Zearin! 👋 

This PR swaps chalk for [Turbocolor](https://github.com/jorgebucaran/turbocolor).

Turbocolor will give you a small perf boost as it loads _>20x_ faster and applies styles _>18x_ faster than chalk for the same API.

<pre>
# Load Time
chalk: 15.190ms
turbocolor: 0.777ms

# All Colors
chalk × 8,729 ops/sec
turbocolor × 158,383 ops/sec

# Chained Colors
chalk × 1,838 ops/sec
turbocolor × 39,830 ops/sec

# Nested Colors
chalk × 4,049 ops/sec
turbocolor × 59,833 ops/sec
</pre>

Cheers!

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Tests failed because turbocolor currently doesn't work on Node.js v4 or v0.12. I could easily add v4 support with "use strict", but supporting seems extreme v0.12.0. What do you think?

**Comment by jorgebucaran** [comment]
Node.js v4 support added! 🎉

**Comment by Ajedi32** [comment]
We're planning to drop support for Node 0.12 (and v4) in the next major release. I think we'll probably do one more v2 release before then, so going to hold off on merging this for now.

**Comment by jorgebucaran** [comment]
Sounds good! 👍

**Comment by jorgebucaran** [comment]
👋 @Ajedi32 The name of the library was changed to colorette. I can fix it up in no time -- just let me know when the time is good.

**Comment by webketje** [comment]
Turbocolor has now been deprecated, but recommends [colorette](https://www.npmjs.com/package/colorette).
One is not inherently better than the other except marginal perf times, or in case the bundle is compiled.

**Comment by webketje** [comment]
Closing as we've gone with an upgraded chalk version

**Pull request closed without merging**
