### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Setup coverage

### CODE REVIEW

**Comment by Ajedi32** [comment]
Looks great! :+1:

**Comment by Ajedi32** [comment]
Aside from merging this, is there anything the project maintainers have to do to set up coveralls/david-dm?

**Comment by AdrieanKhisbe** [comment]
just log with their github account, and activate the repo :)
nothing more

**Comment by Ajedi32** [comment]
Awesome! @lambtron, can you look into this?

Also, I think the badge links may actually need to be updated, since we recently moved this repo from segmentio/metalsmith to metalsmith/metalsmith.

**Comment by AdrieanKhisbe** [comment]
Indeed. taking care of this now =)

**Comment by Ajedi32** [comment]
Hmm, Travis seems to be unaware that the repo moved. The updated URL for that badge broke it. :confused:

**Comment by lambtron** [comment]
Ah i'll reupdate the info in travis. Thanks for reminding me!

**Comment by Ajedi32** [comment]
@lambtron Great, looks like the update worked. Now we just need Coveralls access enabled (https://github.com/organizations/metalsmith/settings/oauth_application_policy) and we can merge this.

**Comment by lambtron** [comment]
Done!

**Comment by lambtron** [comment]
Accidentally closed it. Feel free to merge!

**Comment by Ajedi32** [comment]
Looks good.

**Pull request merged**
