### PR TITLE
Logo Proposal

### PR DESCRIPTION
**Pull request by cameronjroe**
- A proposal for a svg and png logo. Feedback welcome.

### CODE REVIEW

**Comment by Ajedi32** [comment]
Looks pretty slick. The font in the SVG logo seems to be messed up though. Maybe it's just my browser, or I don't have the right fonts installed or something:

screenshot-github com 2015-11-05 15-31-54

**Comment by cameronjroe** [comment]
@Ajedi32 Thanks! Looks like Firefox wants the font self-contained. I base64 encoded it in the svg. It should be working now.

**Comment by Ajedi32** [comment]
Looks good. :+1:

**Comment by AdrieanKhisbe** [comment]
Personally I prefer that logo represent the **hammer** 🛠 and the **craftman** 👷 that use it :)

cf https://en.wikipedia.org/wiki/Metalsmith

**Comment by cameronjroe** [comment]
Sure, do you have a design you'd like to propose?

**Comment by AdrieanKhisbe** [comment]
not yet ;)
But I'll work on some draft in the two days to come. :)

**Comment by AdrieanKhisbe** [comment]
Do you have some ideas, suggestions? :)

**Comment by AdrieanKhisbe** [comment]
cf https://twitter.com/cdixon/status/686808901308698624
> "Like all artisans, a blacksmith needs tools, but  blacksmiths are unique in that they make their own tools." 
 "technology is the process of creating ever more powerful technology using tools from prior rounds of innovation" 
 "disciplines like software that make their own tools generate accelerating returns due to this "Blacksmith Effect"

Hence motivation to have both tool and craftman :)

**Comment by ianstormtaylor** [comment]
Hey all, Metalsmith already has a logo (the wordmark) that we use. (You can see it on the website.) I don't think we need to add an additional graphic to it. 

@lambtron There is actually a `metalsmith-logo` repository in Segment's GitHub org that you might want to move over into the organization. (Might not hurt to move all of the metalsmith plugins owned by Segment as well, but your call there.)

If someone wants to add that existing logo to the Readme that sounds cool!

**Pull request closed without merging**
