### PR TITLE
erroring test reading symbolic link to dir

### PR DESCRIPTION
**Pull request by edrex**
~~This is a bug report, in the form of an erroring test, but not a fix.~~

The first thing I tried with Metalsmith was to symlink a dir into my src dir, like this:

```
src/dir => ../dir
dir/index.md
```

This results in an error, I think because the recursive read doesn't recognize the symlink as a dir and tries to read it as a file. The test case shows the error:

```
  1) Metalsmith #read should traverse a symbolic link to a directory:
     Failed to read the file at: /Users/eric/Projects/metalsmith/test/fixtures/read-symbolic-link/src/dir

EISDIR: illegal operation on a directory, read
  Error: Failed to read the file at: test/fixtures/read-symbolic-link/src/dir

  EISDIR: illegal operation on a directory, read
      at Error (native)
```

I had a look the read function, but got a bit dizzy with all the yields and such.

### CODE REVIEW

**Comment by edrex** [comment]
Upstream issue: jergason/recursive-readdir#32

**Comment by edrex** [comment]
Fixed upstream: https://github.com/jergason/recursive-readdir/pull/33

**Comment by edrex** [comment]
@Ajedi32 you might be interested since you have recent commits to recursive-readdir.

Consider this PR as throwaway, since the upstream change has tests.

**Comment by edrex** [comment]
or i guess adding a test here too wouldn't hurt.

**Comment by edrex** [comment]
Fixed upstream. Once there's a release I'll rev recursive-readdir here.

**Comment by edrex** [comment]
Hi @jmatsushita, I haven't looked at the handling for plugins. 

I just pushed a commit which depends on the current recursive-readdir HEAD, which has a fix for the original issue.

Can you try it and see if it resolves your issue?

**Comment by edrex** [comment]
Ok, upstream was revved so this is ready for review. @Ajedi32 I guess?

**Comment by jmatsushita** [comment]
Hi @edrex seems to fix it. Thanks!

**Comment by Mr0grog** [comment]
Hi all, a client I’m working with is currently maintaining a complete fork of metalsmith *just to work around this issue.* That’s not great and it would be really lovely to see this shipped.

**Comment by Ajedi32** [comment]
Yeah, I've been pretty busy lately with final exams at college so I haven't gotten around to fixing this yet. If you ask in the Metalsmith slack channel there may be someone else who can handle it, otherwise I'll probably get to it in a week or so after finals are over.

**Comment by Mr0grog** [comment]
:thumbsup: Thanks for the status update. Good to know that it’s on your radar; I was mainly just worried nobody was paying attention since it’s been sitting with no feedback for a month.

**Comment by edrex** [comment]
This is ready to go, PTAL @Ajedi32 thanks much

**Comment by Ajedi32** [comment]
Looks good. :+1:

**Pull request merged**
