### PR TITLE
Add more Node versions to Travis

### PR DESCRIPTION
**Pull request by Ajedi32**
Node's been putting out quite a few new releases lately. Might as well add them to the tests...

### CODE REVIEW

**Comment by woodyrew** [comment]
Good work :+1:

**Comment by RobLoach** [comment]
Couldn't we just target `4` and `5`? Have the latest in each major version?

**Comment by Ajedi32** [comment]
Sure. That would save us the trouble of having to constantly update the `.travis.yml` file with new versions. The downside though is that if say, something was failing on 5.3 but not 5.2 (for whatever reason), the build could start failing for seemingly no reason. I guess the chances of that happening are pretty small though, since minor releases are supposed to be backwards compatible with each other as per semver.

Personally I'm fine doing it either way.

**Comment by Ajedi32** [comment]
I'm just going to merge this for now, and then I'll open a separate PR to discuss the merits of just testing the latest version of each revision.

**Pull request merged**
